apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: tutorial
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user05-order:latest
          ports:
            - containerPort: 8080
          env:
            - name: configurl
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: url
